apiVersion: apps/v1
kind: Deployment
metadata:
  name: okard-backend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      
      initContainers:
        - name: alembic-upgrade
          image: ghcr.io/o-kard/okard-backend:latest
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: okard-backend-secrets

      containers:
        - name: okard-backend
          image: ghcr.io/o-kard/okard-backend:latest
          envFrom:
            - secretRef:
                name: okard-backend-secrets
