version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: local-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: okard_admin
      MINIO_ROOT_PASSWORD: okard5246
    volumes:
      - minio_local_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  minio-setup:
    image: minio/mc:latest
    container_name: local-minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'รอ MinIO สตาร์ท 5 วินาที...';
      sleep 5;
      echo 'กำลังเชื่อมต่อและสร้าง Bucket...';
      mc alias set myminio http://minio:9000 okard_admin okard5246;
      mc mb myminio/crowdfunding-bucket || true; 
      mc anonymous set download myminio/crowdfunding-bucket;
      echo 'สร้าง Bucket อัตโนมัติเสร็จสมบูรณ์!';
      exit 0;
      "

volumes:
  minio_local_data: