version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: local-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: okard_admin
      MINIO_ROOT_PASSWORD: okard5246
    volumes:
      - minio_local_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_local_data: