apiVersion: v1
kind: Service
metadata:
  name: okard-backend-svc
  labels:
    app: okard-backend
spec:
  selector:
    app: okard-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
