"""move_embedding_to_new_table

Revision ID: 1151ec6e56b1
Revises: 25488cf16d55
Create Date: 2026-01-31 13:08:06.576544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1151ec6e56b1'
down_revision: Union[str, Sequence[str], None] = '25488cf16d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user_post_view') # SKIPPED: Incorrectly detected drop
    
    # 1. Create new table (Using raw SQL to handle existence check)
    op.execute("""
        CREATE TABLE IF NOT EXISTS post_embedding (
            post_id UUID NOT NULL,
            embedding TEXT,
            PRIMARY KEY (post_id),
            CONSTRAINT fk_post_embedding_post FOREIGN KEY (post_id) REFERENCES post (id)
        )
    """)
    # op.create_table('post_embedding',
    # sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    # sa.PrimaryKeyConstraint('post_id')
    # )
    
    # 2. Migrate data
    op.execute("INSERT INTO post_embedding (post_id, embedding) SELECT id, embedding FROM post WHERE embedding IS NOT NULL")

    # 3. Drop old column
    op.drop_column('post', 'embedding')
    
    # Other detected changes (kept safely)
    # op.create_foreign_key(None, 'model', 'post', ['post_id'], ['id'])
    # op.create_foreign_key(None, 'notification', 'user', ['actor_id'], ['id'])
    # op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add back column
    op.add_column('post', sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True))
    
    # 2. Restore data
    op.execute("UPDATE post SET embedding = post_embedding.embedding FROM post_embedding WHERE post.id = post_embedding.post_id")
    
    # 3. Drop new table
    op.drop_table('post_embedding')

    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.create_table('user_post_view',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('user_post_view_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_post_view_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_post_view_pkey'))
    )
    # ### end Alembic commands ###
