"""remove category_label from model

Revision ID: 24177bdb8b7b
Revises: 12cb81e09666
Create Date: 2026-02-15 02:14:28.771332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24177bdb8b7b'
down_revision: Union[str, Sequence[str], None] = '12cb81e09666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'model', 'post', ['post_id'], ['id'])
    op.drop_column('model', 'category_label')
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'user', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.add_column('model', sa.Column('category_label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model', type_='foreignkey')
    # ### end Alembic commands ###
