"""refactor post state

Revision ID: 28e0a0d32bf0
Revises: ecec37efc28e
Create Date: 2026-03-01 18:52:26.408935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28e0a0d32bf0'
down_revision: Union[str, Sequence[str], None] = 'ecec37efc28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'status')
    
    # Manually handle PostState enum update
    op.execute("ALTER TYPE poststate RENAME TO poststate_old")
    op.execute("CREATE TYPE poststate AS ENUM('draft', 'published', 'fail', 'success', 'suspend')")
    
    # Map 'archived' to 'suspend', and cast the rest
    op.execute((
        "ALTER TABLE post ALTER COLUMN state TYPE poststate USING "
        "CASE "
        "WHEN state::text = 'archived' THEN 'suspend'::poststate "
        "ELSE state::text::poststate "
        "END"
    ))
    op.execute("DROP TYPE poststate_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE poststate RENAME TO poststate_new")
    op.execute("CREATE TYPE poststate AS ENUM('draft', 'published', 'archived')")
    
    op.execute((
        "ALTER TABLE post ALTER COLUMN state TYPE poststate USING "
        "CASE "
        "WHEN state::text IN ('fail', 'success', 'suspend') THEN 'draft'::poststate "
        "ELSE state::text::poststate "
        "END"
    ))
    op.execute("DROP TYPE poststate_new")
    
    op.add_column('post', sa.Column('status', postgresql.ENUM('active', 'inactive', 'suspended', name='poststatus'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
