"""update_schema_all

Revision ID: 2a953ee13f96
Revises: 81851fd0c910
Create Date: 2025-12-14 13:51:43.649658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a953ee13f96'
down_revision: Union[str, Sequence[str], None] = '81851fd0c910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    reference_type = postgresql.ENUM('post', 'campaign', 'user', 'progress', 'reward', name='referencetype', create_type=False)
    reference_type.create(op.get_bind(), checkfirst=True)
    
    if 'imageHandler' not in existing_tables and 'imagehandler' not in existing_tables:
        op.create_table('imageHandler',
            sa.Column('image_id', sa.UUID(), nullable=False),
            sa.Column('reference_id', sa.UUID(), nullable=False),
            sa.Column('type', reference_type, nullable=False),
            sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
            sa.PrimaryKeyConstraint('image_id', 'reference_id', 'type')
        )

    # Data migration
    op.execute("INSERT INTO \"imageHandler\" (image_id, reference_id, type) SELECT id, post_id, 'post'::referencetype FROM image WHERE post_id IS NOT NULL")
    op.execute("INSERT INTO \"imageHandler\" (image_id, reference_id, type) SELECT id, user_id, 'user'::referencetype FROM image WHERE user_id IS NOT NULL")
    op.execute("INSERT INTO \"imageHandler\" (image_id, reference_id, type) SELECT id, campaign_id, 'campaign'::referencetype FROM image WHERE campaign_id IS NOT NULL")
    op.execute("INSERT INTO \"imageHandler\" (image_id, reference_id, type) SELECT id, reward_id, 'reward'::referencetype FROM image WHERE reward_id IS NOT NULL")
    
    report_type = postgresql.ENUM('edit', 'problem', name='reporttype', create_type=False)
    report_type.create(op.get_bind(), checkfirst=True)
    
    if 'report' not in existing_tables:
        op.create_table('report',
        sa.Column('post_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('type', report_type, nullable=False),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id', 'type')
    )
    op.add_column('campaign', sa.Column('display_order', sa.Integer(), nullable=True))
    op.drop_column('campaign', 'order')
    op.add_column('image', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    op.drop_constraint(op.f('image_reward_id_fkey'), 'image', type_='foreignkey')
    op.drop_constraint(op.f('image_campaign_id_fkey'), 'image', type_='foreignkey')
    op.drop_constraint(op.f('image_user_id_fkey'), 'image', type_='foreignkey')
    op.drop_constraint(op.f('image_post_id_fkey1'), 'image', type_='foreignkey')
    op.drop_column('image', 'user_id')
    op.drop_column('image', 'post_id')
    op.drop_column('image', 'reward_id')
    op.drop_column('image', 'order')
    op.drop_column('image', 'campaign_id')
    op.add_column('model', sa.Column('model_version', sa.String(), nullable=True))
    op.alter_column('post', 'effective_start_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('post', 'effective_end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('reward', sa.Column('display_order', sa.Integer(), nullable=True))
    op.drop_column('reward', 'order')
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('reward', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reward', 'display_order')
    op.alter_column('post', 'effective_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('post', 'effective_start_from',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('model', 'model_version')
    op.add_column('image', sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('image', sa.Column('reward_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('image_post_id_fkey1'), 'image', 'post', ['post_id'], ['id'])
    op.create_foreign_key(op.f('image_user_id_fkey'), 'image', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('image_campaign_id_fkey'), 'image', 'campaign', ['campaign_id'], ['id'])
    op.create_foreign_key(op.f('image_reward_id_fkey'), 'image', 'reward', ['reward_id'], ['id'])
    op.drop_column('image', 'display_order')
    op.add_column('campaign', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('campaign', 'display_order')
    op.drop_table('report')
    op.drop_table('imageHandler')
    # ### end Alembic commands ###
