"""Add report to ReferenceType and files to Report

Revision ID: 4cfac35350f2
Revises: aefbc62a9dd1
Create Date: 2026-02-08 19:24:57.668251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cfac35350f2'
down_revision: Union[str, Sequence[str], None] = 'aefbc62a9dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual addition of Enum value
    op.execute("COMMIT")  # ALTER TYPE cannot run in a transaction block
    op.execute("ALTER TYPE \"referencetype\" ADD VALUE 'report'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres ENUMs do not support removing values easily.
    pass
    # ### end Alembic commands ###
