"""add_proposed_changes_jsonb

Revision ID: 5b84e7e725f1
Revises: c761b3fdeb32
Create Date: 2026-01-03 18:39:49.533684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b84e7e725f1'
down_revision: Union[str, Sequence[str], None] = 'c761b3fdeb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check existing columns
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('edit_request')]

    if 'proposed_changes' not in columns:
        op.add_column('edit_request', sa.Column('proposed_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edit_request', 'proposed_changes')
    # ### end Alembic commands ###
