"""init schema

Revision ID: 81851fd0c910
Revises: 
Create Date: 2025-12-12 23:44:23.031574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81851fd0c910'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'campaign', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contributor', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contributor', 'post', ['post_id'], ['id'])
    op.alter_column('country', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('country', 'en_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('country', 'iso3166_2',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('image', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'image', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reward', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.alter_column('image', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country', 'iso3166_2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('country', 'en_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('country', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'contributor', type_='foreignkey')
    op.drop_constraint(None, 'contributor', type_='foreignkey')
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    # ### end Alembic commands ###
