"""split_edit_request_and_report

Revision ID: a5f91d769e94
Revises: 2a953ee13f96
Create Date: 2026-01-02 22:45:45.741092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f91d769e94'
down_revision: Union[str, Sequence[str], None] = '2a953ee13f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums that are used in add_column or modified
    ka_status = sa.Enum('pending', 'investigating', 'resolved', 'dismissed', name='reportstatus')
    ka_status.create(op.get_bind(), checkfirst=True)
    
    # Create Enums for new tables explicitly to be safe (though create_table usually handles it)
    # edit_req_status = sa.Enum('pending', 'approved', 'rejected', 'expired', 'cancelled', name='editrequeststatus')
    # edit_req_status.create(op.get_bind(), checkfirst=True)
    # vote_dec = sa.Enum('approve', 'reject', name='votedecision')
    # vote_dec.create(op.get_bind(), checkfirst=True)

    # Add new values to ReportType
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE reporttype ADD VALUE IF NOT EXISTS 'spam'")
        op.execute("ALTER TYPE reporttype ADD VALUE IF NOT EXISTS 'inappropriate'")

    op.create_table('edit_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'cancelled', name='editrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_request_approver',
    sa.Column('edit_request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edit_request_id'], ['edit_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('edit_request_id', 'user_id')
    )
    op.create_table('edit_request_vote',
    sa.Column('edit_request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', name='votedecision'), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['edit_request_id'], ['edit_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('edit_request_id', 'user_id')
    )
    op.add_column('report', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('report', sa.Column('reporter_id', sa.UUID(), nullable=False))
    op.add_column('report', sa.Column('status', sa.Enum('pending', 'investigating', 'resolved', 'dismissed', name='reportstatus'), nullable=False))
    op.add_column('report', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('report', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('report', sa.Column('resolver_id', sa.UUID(), nullable=True))

    # Manually drop old composite PK
    # Name is usually 'report_pkey'
    op.drop_constraint('report_pkey', 'report', type_='primary')
    
    op.alter_column('report', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
               
    # Create new PK on 'id'
    op.create_primary_key('report_pkey', 'report', ['id'])
    op.alter_column('report', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('report_user_id_fkey'), 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'user', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['resolver_id'], ['id'])
    op.drop_column('report', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key(op.f('report_user_id_fkey'), 'report', 'user', ['user_id'], ['id'])
    op.alter_column('report', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('report', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('report', 'resolver_id')
    op.drop_column('report', 'resolved_at')
    op.drop_column('report', 'admin_notes')
    op.drop_column('report', 'status')
    op.drop_column('report', 'reporter_id')
    op.drop_column('report', 'id')
    op.drop_table('edit_request_vote')
    op.drop_table('edit_request_approver')
    op.drop_table('edit_request')
    
    # Convert 'status' back to varchar if needed or drop type
    # Since we can't easily undo "ADD VALUE" to enums in Postgres without dropping logic, we skip reverting reporttype values.
    
    sa.Enum(name='reportstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='editrequeststatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='votedecision').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
