"""split_edit_request_and_report

Revision ID: a5f91d769e94
Revises: 2a953ee13f96
Create Date: 2026-01-02 22:45:45.741092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f91d769e94'
down_revision: Union[str, Sequence[str], None] = '2a953ee13f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums safely using raw SQL
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE reportstatus AS ENUM ('pending', 'investigating', 'resolved', 'dismissed');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)
    ka_status = postgresql.ENUM('pending', 'investigating', 'resolved', 'dismissed', name='reportstatus', create_type=False)

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE editrequeststatus AS ENUM ('pending', 'approved', 'rejected', 'expired', 'cancelled');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)
    edit_req_status = postgresql.ENUM('pending', 'approved', 'rejected', 'expired', 'cancelled', name='editrequeststatus', create_type=False)

    op.execute("""
    DO $$ BEGIN
        CREATE TYPE votedecision AS ENUM ('approve', 'reject');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)
    vote_dec = postgresql.ENUM('approve', 'reject', name='votedecision', create_type=False)

    # Add new values to ReportType
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE reporttype ADD VALUE IF NOT EXISTS 'spam'")
        op.execute("ALTER TYPE reporttype ADD VALUE IF NOT EXISTS 'inappropriate'")

    # Check existing tables
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'edit_request' not in existing_tables:
        op.create_table('edit_request',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('post_id', sa.UUID(), nullable=False),
        sa.Column('requester_id', sa.UUID(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('status', edit_req_status, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
        sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'edit_request_approver' not in existing_tables:
        op.create_table('edit_request_approver',
        sa.Column('edit_request_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('contribution_amount', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['edit_request_id'], ['edit_request.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('edit_request_id', 'user_id')
        )

    if 'edit_request_vote' not in existing_tables:
        op.create_table('edit_request_vote',
        sa.Column('edit_request_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('decision', vote_dec, nullable=False),
        sa.Column('voted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('comment', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['edit_request_id'], ['edit_request.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('edit_request_id', 'user_id')
        )
    op.add_column('report', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('report', sa.Column('reporter_id', sa.UUID(), nullable=False))
    op.add_column('report', sa.Column('status', ka_status, nullable=False))
    op.add_column('report', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('report', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('report', sa.Column('resolver_id', sa.UUID(), nullable=True))

    # Manually drop old composite PK
    # Name is usually 'report_pkey'
    op.drop_constraint('report_pkey', 'report', type_='primary')
    
    op.alter_column('report', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
               
    # Create new PK on 'id'
    op.create_primary_key('report_pkey', 'report', ['id'])
    op.alter_column('report', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('report_user_id_fkey'), 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'user', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['resolver_id'], ['id'])
    op.drop_column('report', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key(op.f('report_user_id_fkey'), 'report', 'user', ['user_id'], ['id'])
    op.alter_column('report', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('report', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('report', 'resolver_id')
    op.drop_column('report', 'resolved_at')
    op.drop_column('report', 'admin_notes')
    op.drop_column('report', 'status')
    op.drop_column('report', 'reporter_id')
    op.drop_column('report', 'id')
    op.drop_table('edit_request_vote')
    op.drop_table('edit_request_approver')
    op.drop_table('edit_request')
    
    # Convert 'status' back to varchar if needed or drop type
    # Since we can't easily undo "ADD VALUE" to enums in Postgres without dropping logic, we skip reverting reporttype values.
    
    sa.Enum(name='reportstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='editrequeststatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='votedecision').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
