"""creator_edit_request_handle

Revision ID: ae6c5c91432a
Revises: 61f9be0df03b
Create Date: 2026-03-30 19:26:09.180927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6c5c91432a'
down_revision: Union[str, Sequence[str], None] = '61f9be0df03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_request', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_request', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
