"""Add updated_at to progress

Revision ID: aefbc62a9dd1
Revises: fb35cda0ed2b
Create Date: 2026-02-01 17:15:48.115839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aefbc62a9dd1'
down_revision: Union[str, Sequence[str], None] = 'fb35cda0ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'updated_at')
    # ### end Alembic commands ###
