"""add recommend table

Revision ID: b31af9ce7cf1
Revises: 46983538594f
Create Date: 2026-01-19 23:44:44.736910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b31af9ce7cf1'
down_revision: Union[str, Sequence[str], None] = '46983538594f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column("embedding", sa.Text(), nullable=True)
    )

    op.create_table(
        "user_post_view",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("post_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "viewed_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    op.create_index(
        "idx_user_post_view_user",
        "user_post_view",
        ["user_id"],
    )

    op.create_index(
        "idx_user_post_view_user_time",
        "user_post_view",
        ["user_id", "viewed_at"],
    )

    op.create_index(
        "idx_user_post_view_post",
        "user_post_view",
        ["post_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
