"""Add role column to user table

Revision ID: b5e16dae4325
Revises: 2a953ee13f96
Create Date: 2026-01-04 22:05:02.961183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e16dae4325'
down_revision: Union[str, Sequence[str], None] = '2a953ee13f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up orphaned rows before adding FKs
    op.execute("DELETE FROM campaign WHERE post_id NOT IN (SELECT id FROM post)")
    op.execute("DELETE FROM contributor WHERE post_id NOT IN (SELECT id FROM post)")
    op.execute("DELETE FROM contributor WHERE user_id NOT IN (SELECT id FROM \"user\")")
    op.execute("DELETE FROM comment WHERE post_id NOT IN (SELECT id FROM post)")
    op.execute("DELETE FROM comment WHERE user_id NOT IN (SELECT id FROM \"user\")")
    op.execute("DELETE FROM comment_like WHERE user_id NOT IN (SELECT id FROM \"user\")")
    op.execute("DELETE FROM notification WHERE post_id NOT IN (SELECT id FROM post)")
    op.execute("DELETE FROM payment WHERE post_id NOT IN (SELECT id FROM post)")
    op.execute("DELETE FROM payment WHERE user_id NOT IN (SELECT id FROM \"user\")")
    op.execute("DELETE FROM reward WHERE post_id NOT IN (SELECT id FROM post)")
    
    op.create_foreign_key(None, 'campaign', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contributor', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contributor', 'post', ['post_id'], ['id'])
    op.alter_column('country', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('country', 'en_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('country', 'iso3166_2',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'notification', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'reward', 'post', ['post_id'], ['id'])
    op.add_column('user', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.alter_column('country', 'iso3166_2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('country', 'en_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('country', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'contributor', type_='foreignkey')
    op.drop_constraint(None, 'contributor', type_='foreignkey')
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    # ### end Alembic commands ###
