"""user&creator update

Revision ID: bed7fdde57c0
Revises: e0ea7daa3ca7
Create Date: 2026-01-25 23:58:30.830033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed7fdde57c0'
down_revision: Union[str, Sequence[str], None] = 'e0ea7daa3ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name_override', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('campaign_number', sa.Integer(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus', create_type=False), nullable=True),
    sa.Column('verification_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'banned', name='userstatus'), nullable=True))
    op.drop_column('user', 'user_description')
    op.drop_column('user', 'campaign_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('campaign_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('user_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'status')
    op.drop_table('creators')
    # ### end Alembic commands ###
