"""remove_resolver_id_from_report

Revision ID: c761b3fdeb32
Revises: a5f91d769e94
Create Date: 2026-01-02 22:55:14.334251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c761b3fdeb32'
down_revision: Union[str, Sequence[str], None] = 'a5f91d769e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('report_resolver_id_fkey'), 'report', type_='foreignkey')
    op.drop_column('report', 'resolver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('resolver_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('report_resolver_id_fkey'), 'report', 'user', ['resolver_id'], ['id'])
    # ### end Alembic commands ###
