"""add display_changes to edit_request

Revision ID: c857938f4224
Revises: d259a3609bba
Create Date: 2026-01-25 16:59:29.078199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c857938f4224'
down_revision: Union[str, Sequence[str], None] = 'd259a3609bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check existing columns
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('edit_request')]

    if 'display_changes' not in columns:
        op.add_column('edit_request', sa.Column('display_changes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edit_request', 'display_changes')
    # ### end Alembic commands ###
