"""add expires_at to edit_request

Revision ID: d259a3609bba
Revises: 5b84e7e725f1
Create Date: 2026-01-04 17:16:19.483943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd259a3609bba'
down_revision: Union[str, Sequence[str], None] = '5b84e7e725f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check existing columns
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('edit_request')]

    if 'expires_at' not in columns:
        op.add_column('edit_request', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edit_request', 'expires_at')
    # ### end Alembic commands ###
