"""fix user creator table

Revision ID: e0e74576ac35
Revises: 304dbe1fd5f7
Create Date: 2026-02-07 23:38:05.746303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e74576ac35'
down_revision: Union[str, Sequence[str], None] = '304dbe1fd5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creators', 'updated_at')
    op.drop_column('creators', 'display_name_override')
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('user', 'creator', 'admin', name='userrole'),
               existing_nullable=True,
               postgresql_using='role::userrole')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('user', 'creator', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('user', 'updated_at')
    op.add_column('creators', sa.Column('display_name_override', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('creators', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
