"""add status suspended in Post

Revision ID: e0ea7daa3ca7
Revises: b5e16dae4325
Create Date: 2026-01-14 22:38:45.690270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ea7daa3ca7'
down_revision: Union[str, Sequence[str], None] = 'b5e16dae4325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE poststatus ADD VALUE IF NOT EXISTS 'suspended'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
